### ISSUE TITLE
Minimizer associated with NEB

### ISSUE THREAD

**Issue by smcantab** [pele-python/pele#145]
@js850 it seems that the optimizer used by NEB is mylbfgs, but your comment seems to recommend not to:

" scipy.lbfgs_b seems to work with NEB pretty well, but lbfgs_py and mylbfgs tend to fail.  If you must use one of those try, e.g. maxErise = 1., maxstep=0.01, tol=1e-2 "

at this line:

https://github.com/pele-python/pele/blob/master/pele/transition_states/_NEB.py#L161

is mylfbgs actually the default? Should I change it to scipy.lbfgs_b? Just looking for ways to make NEB a bit faster, it's very slow at the moment for my application

**Comment by smcantab** [comment]
98% of the computation time is due to calls to the potential getEnergyGradient, so unless changing minimiser will significantly reduce the number of potential calls, it's not gonna make much difference. I just have to launch the calculations on the gpu cluster when tensorflow is installed by IT. Closing for now, but I am still curious about the comment.

**Comment by js850** [comment]
yeah, I can't remember why I wrote that comment, it should probably be removed.  

Since the NEB forces are not actually gradients of any potential you wouldn't expect a line search to be effective.  So you would really expect the pele lbfgs versions with backtracking linesearch to be superior to scipy lbfgs.  But some of those parameters, especially maxErise are probably important.  Maybe mylbfgs wasn't working for me with NEB because I didn't have those set properly.

**Comment by smcantab** [comment]
ok but now it is the default one, and seems to work, so I assume that the
parameters are set properly?
